# Generated by Django 5.2 on 2025-06-02 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoatingInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface_type', models.CharField(choices=[('steel', 'Steel'), ('concrete', 'Concrete'), ('wood', 'Wood'), ('other', 'Other')], max_length=50)),
                ('coating_type', models.CharField(choices=[('epoxy', 'Epoxy'), ('polyurethane', 'Polyurethane'), ('zinc', 'Zinc'), ('other', 'Other')], max_length=50)),
                ('surface_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('surface_preparation', models.TextField()),
                ('coating_thickness', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('visual_inspection', models.BooleanField(default=False)),
                ('adhesion_test', models.BooleanField(default=False)),
                ('adhesion_test_results', models.TextField(blank=True)),
                ('defects_found', models.BooleanField(default=False)),
                ('defect_description', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('passed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_method', models.CharField(blank=True, max_length=50)),
                ('application_time_begin', models.TimeField(blank=True, null=True)),
                ('application_time_end', models.TimeField(blank=True, null=True)),
                ('wft_mils', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mix_number', models.CharField(blank=True, max_length=50)),
                ('comp_a_batch', models.CharField(blank=True, max_length=50)),
                ('comp_b_batch', models.CharField(blank=True, max_length=50)),
                ('mix_time', models.TimeField(blank=True, null=True)),
                ('act_induct_time', models.TimeField(blank=True, null=True)),
                ('pot_life', models.IntegerField(blank=True, null=True)),
                ('quantity_used', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('witnessed', models.BooleanField(default=False)),
                ('backfill_used', models.BooleanField(default=False)),
                ('rock_shield_used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Coating Inspection',
                'verbose_name_plural': 'Coating Inspections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoatingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='coating_photos/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='coating.coatinginspection')),
            ],
            options={
                'verbose_name': 'Coating Photo',
                'verbose_name_plural': 'Coating Photos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyCoatingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('contractor', models.CharField(blank=True, max_length=255, null=True)),
                ('report_number', models.CharField(blank=True, max_length=50, null=True)),
                ('oq_personnel', models.CharField(blank=True, max_length=255, null=True)),
                ('facility_id', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_order', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(max_length=255)),
                ('qa_inspector', models.CharField(blank=True, max_length=255, null=True)),
                ('weather_conditions', models.CharField(max_length=255)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('finalized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Coating Report',
                'verbose_name_plural': 'Daily Coating Reports',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CoatingOversightItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'N/A')], max_length=3)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oversight_items', to='coating.dailycoatingreport')),
            ],
            options={
                'verbose_name': 'Coating Oversight Item',
                'verbose_name_plural': 'Coating Oversight Items',
                'ordering': ['item_number'],
            },
        ),
        migrations.AddField(
            model_name='coatinginspection',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='coating.dailycoatingreport'),
        ),
    ]
