# Generated by Django 5.2 on 2025-05-04 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0007_alter_punchlistitem_end_station_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PunchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.IntegerField(blank=True, null=True)),
                ('spread', models.CharField(blank=True, max_length=100, null=True)),
                ('inspector', models.CharField(blank=True, max_length=100, null=True)),
                ('start_station', models.CharField(blank=True, max_length=100, null=True)),
                ('end_station', models.CharField(blank=True, max_length=100, null=True)),
                ('feature', models.CharField(blank=True, max_length=200, null=True)),
                ('issue', models.TextField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspector_signoff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punchlist_signoffs_new', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punchlist_items_new', to='reports.report')),
            ],
            options={
                'ordering': ['item_number'],
            },
        ),
    ]
