# Generated by Django 5.2 on 2025-05-24 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcreteReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('weather_conditions', models.CharField(max_length=255)),
                ('daily_activities', models.TextField()),
                ('report_type', models.CharField(blank=True, max_length=100, null=True)),
                ('facility', models.CharField(blank=True, max_length=255, null=True)),
                ('route', models.CharField(blank=True, max_length=255, null=True)),
                ('spread', models.CharField(blank=True, max_length=255, null=True)),
                ('compliance_level', models.CharField(blank=True, max_length=100, null=True)),
                ('activity_category', models.CharField(blank=True, max_length=100, null=True)),
                ('activity_group', models.CharField(blank=True, max_length=100, null=True)),
                ('activity_type', models.CharField(blank=True, max_length=100, null=True)),
                ('milepost_start', models.CharField(blank=True, max_length=50, null=True)),
                ('milepost_end', models.CharField(blank=True, max_length=50, null=True)),
                ('station_start', models.CharField(blank=True, max_length=50, null=True)),
                ('station_end', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized', models.BooleanField(default=False)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_report',
            },
        ),
        migrations.CreateModel(
            name='ReportDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=100)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
