# Generated by Django 5.2 on 2025-06-15 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportDraft',
        ),
    ]
