# Generated by Django 5.2 on 2025-05-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punchlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='punchlistreport',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
    ]
