# Generated by Django 5.2 on 2025-06-15 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('punchlists', '0002_punchlistreport_finalized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punchlistreport',
            name='author',
        ),
        migrations.DeleteModel(
            name='PunchlistItem',
        ),
        migrations.DeleteModel(
            name='PunchlistReport',
        ),
    ]
