# Generated by Django 5.2 on 2025-05-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='activity_category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='activity_group',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='activity_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='author',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='report',
            name='compliance_level',
            field=models.CharField(default='Acceptable', max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='county',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='facility',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='milepost_end',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='milepost_start',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='other_field_staff',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='report',
            name='precipitation_inches',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='precipitation_type',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(default='Site Inspection', max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='route',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='spread',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='station_end',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='station_start',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='temperature',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='weather_description',
            field=models.TextField(blank=True),
        ),
    ]
