# Generated by Django 5.2 on 2025-05-02 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_activity_category_report_activity_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='activity_category',
        ),
        migrations.RemoveField(
            model_name='report',
            name='activity_group',
        ),
        migrations.RemoveField(
            model_name='report',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='report',
            name='author',
        ),
        migrations.RemoveField(
            model_name='report',
            name='compliance_level',
        ),
        migrations.RemoveField(
            model_name='report',
            name='county',
        ),
        migrations.RemoveField(
            model_name='report',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='report',
            name='milepost_end',
        ),
        migrations.RemoveField(
            model_name='report',
            name='milepost_start',
        ),
        migrations.RemoveField(
            model_name='report',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='report',
            name='other_field_staff',
        ),
        migrations.RemoveField(
            model_name='report',
            name='precipitation_inches',
        ),
        migrations.RemoveField(
            model_name='report',
            name='precipitation_type',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_type',
        ),
        migrations.RemoveField(
            model_name='report',
            name='route',
        ),
        migrations.RemoveField(
            model_name='report',
            name='spread',
        ),
        migrations.RemoveField(
            model_name='report',
            name='state',
        ),
        migrations.RemoveField(
            model_name='report',
            name='station_end',
        ),
        migrations.RemoveField(
            model_name='report',
            name='station_start',
        ),
        migrations.RemoveField(
            model_name='report',
            name='status',
        ),
        migrations.RemoveField(
            model_name='report',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='report',
            name='weather_description',
        ),
    ]
