# Generated by Django 5.2 on 2025-05-04 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_activity_category_report_activity_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PunchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.IntegerField()),
                ('spread', models.CharField(max_length=100)),
                ('inspector', models.CharField(max_length=100)),
                ('start_station', models.CharField(max_length=100)),
                ('end_station', models.CharField(max_length=100)),
                ('feature', models.CharField(max_length=200)),
                ('issue', models.TextField()),
                ('recommendations', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspector_signoff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punchlist_signoffs', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punchlist_items', to='reports.report')),
            ],
            options={
                'ordering': ['item_number'],
            },
        ),
    ]
