# Generated by Django 5.2 on 2025-05-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_punchlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='punchlistitem',
            name='item_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
