# Generated by Django 5.2 on 2025-05-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_report_finalized_alter_punchlistitem_item_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punchlistitem',
            name='end_station',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='punchlistitem',
            name='feature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='punchlistitem',
            name='inspector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='punchlistitem',
            name='issue',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='punchlistitem',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='punchlistitem',
            name='spread',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='punchlistitem',
            name='start_station',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
