# Generated by Django 5.2 on 2025-05-04 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_punchlistitem_end_station_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PunchlistItem',
        ),
    ]
