"""
Django settings for inspectionreports project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-nnb6$&aupre_w8s3h0sgahlz)-j3@saidvu0m_yvjmo4+c!vb^')

# SECURITY WARNING: don't run with debug turned on in production!
# Auto-detect environment: if DATABASE_URL is set (Heroku), use production settings
# Otherwise, use development settings
IS_HEROKU = os.getenv('DATABASE_URL') is not None
DEBUG = os.getenv('DEBUG', 'True' if not IS_HEROKU else 'False').lower() == 'true'

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '192.168.1.203', 'environmental-reporting-system-febba9464fe7.herokuapp.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_nested',
    'corsheaders',
    'core',  # Core functionality
    'users',  # User management
    'photos',  # Global photo handling
    'disciplines.environmental',  # Environmental base app
    'disciplines.environmental.punchlists',  # Punchlist reports
    'disciplines.environmental.swppp',  # SWPPP reports
    'disciplines.coating',  # Coating reports
    'disciplines.welding',  # Welding reports
    'disciplines.utility',  # Utility reports
    'drafts',
]

MIDDLEWARE = [
    # 'inspectionreports.siddleware.HTTPSRedirectMiddleware',  # Custom HTTPS redirect middleware - disabled for development
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'csp.middleware.CSPMiddleware',  # Disable CSP middleware for development
]

ROOT_URLCONF = 'inspectionreports.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
            BASE_DIR / 'frontend' / 'dist',  # Frontend build directory
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'inspectionreports.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL', 'sqlite:///db.sqlite3'),
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'frontend', 'dist'),  # Frontend build directory
    os.path.join(BASE_DIR, 'frontend', 'public'),  # Public static files
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (Uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings - will be overridden by environment-specific settings below
CORS_ALLOWED_ORIGINS = []

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# CSRF trusted origins - will be overridden by environment-specific settings below
CSRF_TRUSTED_ORIGINS = []

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
}

# Security settings for production
if not DEBUG:
    # Production settings
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True
    USE_X_FORWARDED_PORT = True
    USE_X_FORWARDED_PROTO = True
    
    # Enable HSTS for production
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
    
    # Production CORS settings
    CORS_ALLOWED_ORIGINS = [
        "https://environmental-reporting-system-febba9464fe7.herokuapp.com",
    ]
    
    # Production CSRF settings
    CSRF_TRUSTED_ORIGINS = [
        "https://environmental-reporting-system-febba9464fe7.herokuapp.com",
    ]
    
    # Production CSP settings - only enable if middleware is active
    # CSP_DEFAULT_SRC = ("'self'", "https://environmental-reporting-system-febba9464fe7.herokuapp.com")
    # CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "https://environmental-reporting-system-febba9464fe7.herokuapp.com")
    # CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'", "'unsafe-eval'", "https://environmental-reporting-system-febba9464fe7.herokuapp.com")
    # CSP_IMG_SRC = ("'self'", "data:", "https://environmental-reporting-system-febba9464fe7.herokuapp.com")
    # CSP_FONT_SRC = ("'self'", "data:", "https://environmental-reporting-system-febba9464fe7.herokuapp.com")
    # CSP_CONNECT_SRC = ("'self'", "https://environmental-reporting-system-febba9464fe7.herokuapp.com")
    # CSP_MANIFEST_SRC = ("'self'", "https://environmental-reporting-system-febba9464fe7.herokuapp.com")
else:
    # Development settings - COMPLETELY DISABLE HTTPS FOR LOCAL DEVELOPMENT
    SESSION_COOKIE_AGE = 60 * 60 * 24 * 30  # 30 days
    
    # CRITICAL: Disable ALL HTTPS-related settings for development
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_PROXY_SSL_HEADER = None
    USE_X_FORWARDED_HOST = False
    USE_X_FORWARDED_PORT = False
    USE_X_FORWARDED_PROTO = False
    
    # Disable HSTS and other security headers that can cause HTTPS redirects
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    SECURE_CONTENT_TYPE_NOSNIFF = False
    SECURE_BROWSER_XSS_FILTER = False
    X_FRAME_OPTIONS = 'SAMEORIGIN'
    
    # Disable CSP for development to avoid conflicts
    CSP_DEFAULT_SRC = None
    CSP_STYLE_SRC = None
    CSP_SCRIPT_SRC = None
    CSP_IMG_SRC = None
    CSP_FONT_SRC = None
    CSP_CONNECT_SRC = None
    CSP_MANIFEST_SRC = None

    # Development CORS settings - Allow all localhost variations
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://localhost:8000",
        "http://127.0.0.1:8000",
        "http://192.168.1.203:3000",
        "http://192.168.1.203:5173",
        "http://192.168.1.203:8000",
    ]
    
    # Allow all origins for development (more permissive)
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOW_CREDENTIALS = True

    # Development CSRF settings - Allow all localhost variations
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://localhost:8000",
        "http://127.0.0.1:8000",
        "http://192.168.1.203:3000",
        "http://192.168.1.203:5173",
        "http://192.168.1.203:8000",
    ]
    
    # Allow all CSRF origins for development
    CSRF_ALLOW_ALL_ORIGINS = True

# Configure whitenoise
WHITENOISE_USE_FINDERS = True
WHITENOISE_MANIFEST_STRICT = False
WHITENOISE_ALLOW_ALL_ORIGINS = True
