# Generated by Django 5.2 on 2025-05-14 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SWPPPReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(choices=[('routine', 'Routine Weekly Inspection'), ('precip', 'Precipitation Event > 0.25"')], max_length=20)),
                ('inspection_date', models.DateField()),
                ('precipitation_date', models.DateField(blank=True, null=True)),
                ('inspector_name', models.CharField(max_length=255)),
                ('precipitation_rain_gage', models.BooleanField(default=False)),
                ('precipitation_rain', models.BooleanField(default=False)),
                ('precipitation_snow', models.BooleanField(default=False)),
                ('soil_dry', models.BooleanField(default=False)),
                ('soil_wet', models.BooleanField(default=False)),
                ('soil_saturated', models.BooleanField(default=False)),
                ('soil_frozen', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('weather_conditions', models.CharField(blank=True, max_length=255)),
                ('additional_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SWPPPPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='swppp_photos/')),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='swppp.swpppreport')),
            ],
        ),
        migrations.CreateModel(
            name='SWPPPItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('ll_number', models.CharField(blank=True, max_length=100)),
                ('feature_details', models.CharField(blank=True, max_length=255)),
                ('inspector_id', models.CharField(blank=True, max_length=100)),
                ('soil_presently_disturbed', models.BooleanField(default=False)),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('inspection_time', models.TimeField(blank=True, null=True)),
                ('ecd_functional', models.BooleanField(default=False)),
                ('ecd_needs_maintenance', models.BooleanField(default=False)),
                ('date_corrected', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='swppp.swpppreport')),
            ],
        ),
    ]
